Add Software Development Contract - internal
bornfight/README pull request #44
Opened 2020-04-17 15:42 UTC by ibrcko

This document is designed to explain in what manner will software dev. dept. members contribute to a project.

All suggestions are very welcome, especially regarding each role expectations section!

2020-04-17 15:57 UTC, krukru commented
Looks real nice! Please put this draft up on the dev weekly agenda 👍

2020-04-20 16:15 UTC, renatoruk commented
I've previously read the Croatian version and it's awesome. I think other teams and companies would benefit from this approach also. Could be a great candidate for a blog post 😎

2020-04-28 10:43 UTC, napravicukod requested changes

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +-   An official document without which the development shouldn’t be started
```suggestion
-   An official document as an absolute requirement for development to start
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +    -   Which software functionalities are we going to develop?
```suggestion
    -   Which software functionalities are to be developed?
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +    -   There is a “single source of truth” to which all parties can rely upon if a misunderstanding occurs
```suggestion
    -   There is a “single source of truth” for reference in case of misunderstanding
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +    -   A clear difference can be seen between “functionalities agreed upon" and "change requests"
```suggestion
    -   A change request is easier to define
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +    -   A need for back-and-forth communication between a client and us is decreased
```suggestion
    -   A need for back-and-forth communication between the client and our side is decreased
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +        -   I, as a user, have a new client, and I want to store his information. This functionality is used in two
```suggestion
        -   I, as a user, have a new client, and I want to store this client's information. This functionality is used in two
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +    -   _This role brings with it an increased level of responsibility for the software delivery in a predicted
```suggestion
    -   _This role comes with increased level of responsibility for the software delivery in a predicted
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +        -   To know the answer to all of your questions about software requirements, business logic or technical
```suggestion
        -   To know answers to all of your questions about software requirements, business logic or technical
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +    -   Has a lot less responsibility for software delivery
```suggestion
    -   Delivery responsibility is mainly focused on tasks and features, depending on the maker seniority level
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +        -   To communicate its road-block, impediments or requests help
```suggestion
        -   To communicate roadblocks, impediments and ask for help
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +        -   Complete independence while doing its work
```suggestion
        -   Complete autonomy while working
```

2020-04-28 10:43 UTC, napravicukod commented on playbooks/software-development-internal-contract.md
> +        -   To take responsibility for software delivery
```suggestion
        -   To take the final responsibility for software delivery
```

2020-04-30 08:14 UTC, marojeee commented
Another important _process describer_, which should improve our day-to-day work.
Since I already gave my input in the Croatian version, I will just leave a thumbs up as a support for making this document and translating it  👍

2020-09-02 14:50 UTC, krukru commented
Ready to merge?

2024-05-16 15:11 UTC, closed without merging

2024-05-16 15:33 UTC, krukru commented
> Ready to merge?

Guess not :D